### ISSUE TITLE
Need event to signal when decoder underflow has occurred

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#101]
While readyState transitions down from HAVE_ENOUGH_DATA -> HAVE_FUTURE_DATA -> HAVE_CURRENT_DATA (and associated "waiting" event) give apps feedback about potentially necessary adaptation when playback time is reaching the end of continuously playable buffered range, there is no mechanism currently for signaling another case where playback time isn't advancing fast enough (due to underflow, for example).

I'd like web authors to chime in here if they think this would indeed be useful. For example, I think it could be useful in scenarios where decoder could be underprovisioned versus the bitstream (or the environment is dynamic) such that isTypeSupported/canPlayType is insufficient for guaranteeing the decoder can always keep pace.

**Comment by wolenetz** [comment]
@ddorwin, @mounirlamouri this might be more general if such an event were done with some future version of Video/MediaPlaybackQuality that isn't necessarily MSE-specific.

**Comment by mwatson2** [comment]
I propose we close this for lack of input. Detection of underpowered decoder can be achieved through Media Playback Quality.

**Comment by wolenetz** [comment]
I agree.
