### ISSUE TITLE
Non-interoperable behavior regarding invalid ISOBMFF Init Segment

### ISSUE THREAD

**Issue by cconcolato** [w3c/media-source#110]
This issue is related to the ISOBMFF byte stream format. 

By mistake, I generated ISOBMFF init segment, missing the 'ftyp' box. Such content works fine in Chrome and Edge but does not in Safari and Firefox (See [Firefox Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1283984#c22) for how Firefox processes such content).

Given that it works fine in some browsers and that also some standalone players work fine without the ftyp box (GPAC), I wonder if the byte stream format spec for ISOBMFF shouldn't be changed to permit the absence of the ftyp box. It could be assumed that an ftyp box with some default value is present, and the beginning of an init segment could be detected by either the ftyp box or the moov box.

**Comment by wolenetz** [comment]
Chrome's ISOBMFF bytestream parser allows some leniency in some cases where media on the web has been a little problematic (or the Chrome media pipeline doesn't care too much currently about the specifics, such as compatibility constraints around the ftyp box).  Chrome actually has had a bug filed for a while to be more strict around requiring ftyp: https://www.google.com/url?q=http://crbug.com/504514

I think this is simply an implementation bug, not a spec bug. If you can find specific cases (other than, "mistakes" :) ) where ftyp **should** be allowed to be missing from an initialization segment, please reactivate this spec issue.
