### ISSUE TITLE
Use RFC2119 key words in byte stream registry and byte stream specs

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#115]
#52 tracked fixing the main MSE spec. This new issue tracks fixing the byte stream registry and byte stream specs.

**Comment by paulbrucecotton** [comment]
The byte stream registry and the specs it refers to are informative references from MSE and therefore their content is effectively non-normative.  I am not sure it makes sense to spend valuable resources adding RFC2119 key words to non-normative material.

**Comment by wolenetz** [comment]
It's pretty much done already by the time I saw your email :) (See
https://github.com/w3c/media-source/pull/117).
