### ISSUE TITLE
Unecessary step in duration change

### ISSUE THREAD

**Issue by jyavenard** [w3c/media-source#123]
http://w3c.github.io/media-source/#duration-change-algorithm

step 3 "Set old duration to the current value of duration."

is no longer required. this step should be removed and all remaining steps number adjusted

**Comment by wolenetz** [comment]
Yep. Known issue: #106 
I sent a PR (#108) for review earlier this week to fix #106.
Closing this issue as duplicate.

Thanks for reporting this, too :)
