### ISSUE TITLE
Consider removing the revision histories

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#126]
See https://github.com/w3c/encrypted-media/issues/280

Pending guidance for EME (and MSE) from @plehagar for this issue originally reported by @ddorwin for EME.

It might be more useful to retain revision history in just the MSE bytestream specs and registry, if we do decide to remove that history from the main MSE spec doc.

**Comment by jdsmith3000** [comment]
I support removing this on both EME (where it hasn't been updated) and MSE (where it has).
As an alternative, the Web Audio Spec just pulls in a GitHub change log: http://www.w3.org/TR/webaudio/changelog.html

**Comment by wolenetz** [comment]
MSE and byte stream format registry and specs all now include a "commit history" link in the document headers.

I'll prep a PR to remove the revision history section from the 2 MSE specs while contain in: (the main spec, and the ISOBMFF bytestream format spec).
