### ISSUE TITLE
Does MSE ISO-BMFF bytestream spec need updates to include vp09... codec string?

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#183]
See https://github.com/w3c/media-source/issues/180#issuecomment-303812167, copied here:

@kqyang, FYI, we probably need a similar issue for MP4. Will leave that to you.

The [MP4 registry](https://w3c.github.io/media-source/isobmff-byte-stream-format.html#mime-parameters) currently reads:

"MIME-types for this specification must conform to the rules outlined for "audio/mp4" and "video/mp4" in RFC 6381."

**Comment by wolenetz** [comment]
Following the current spec links, RFC 6381 refers video/mp4 to www.mp4ra.org, which includes "vp09" as VPxx "as defined in/by" https://github.com/Netflix/vp9-dash/blob/master/VPCodecISOMediaFileFormatBinding.docx

However, that link appears out of date, and doesn't contain the necessary information to describe a compliant "vp09" codec parameter string for use in MSE spec/API.  I've generated a PR to fix the WebM bytestream spec similarly to directly reference http://www.webmproject.org/vp9/mp4/#codecs-parameter-string (which appears to be a more complete/newer version of the doc than the one referenced by mp4ra).

@kgyang, @FrankGalligan: What is the route forward to make the MSE ISOBMFF byte stream spec allow vp09.xx.xx... codec parameter strings (in isTypeSupported/addSourceBuffer portions of the API)? Does mp4ra simply need an updated reference to a doc, or is there something I'm missing? Who is doing such updates?

**Comment by kqyang** [comment]
Updating www.mp4ra.org should be sufficient, i.e. update it to refer to the v1 spec or the Github page. A request has already been submitted to mp4ra. It should be reflected on mp4ra website soon.

**Comment by wolenetz** [comment]
OK. ISTM this issue is thus external, unless mp4ra rejects the update. If they reject it, please re-activate this issue so we're aware of the change of plans.
