### ISSUE TITLE
Ambiguous behaviour when running sourcebuffer.abort()

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#19]
Migrated from w3c bugzilla tracker. For history prior to migration, please see:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27980

**Comment by jdsmith3000** [comment]
We plan to disallow aborts of a range removal to insure results are deterministic, and separate range removal from duration changes that would currently do an automatic remove.  That affects both this issue and [Issue 20](https://github.com/w3c/media-source/issues/20).

**Comment by jdsmith3000** [comment]
Additionally, aborting range removals should return an error.

**Comment by jdsmith3000** [comment]
@Wolenetz:  It looks like separating automatic range removals on duration change can be accomplished by removing step 3.4.6 in the **Duration change** algorithm.  Returning an error requires some means to tell that a range removal is in progress (a subset of "updating").  That appears to require an additional attribute on SourceBuffer.  Agreed?

**Comment by wolenetz** [comment]
@jdsmith3000 I suspect you're correct that we'll need a way to determine that we're in the process of performing a remove vs an appendbuffer/stream. If an abort() arrives during the processing of a remove, the proposal would be to return an error immediately.
Regarding the similar concern of disallowing range removal as part of duration change (and instead returning an error): I think step 2.4.6.4 of the Duration Change algorithm (in current editor's draft at http://w3c.github.io/media-source/#duration-change-algorithm) needs to be modified to instead of triggering range removal, return error if the new duration is prior to any of the source buffers in SourceBuffers end time.
On further inspection of current MSE editor's draft, even the duration change algorithm's current text seems wrong: it states to run the range removal algorithm, but the duration change algorithm is in MediaSource, and the range removal algorithm is in SourceBuffer.
There is also a note in the duration change algorithm that will need consideration: for text tracks with cues having really long durations: should they prevent duration change to after their cue start time but before their cue start time + cue duration? Ditto for A/V, I suppose.

**Comment by jdsmith3000** [comment]
@Wolenetz To provide an error on `abort()`, we need a range removal state attribute to indicate that removal is in progress.  I think that would best be an internal attribute that's shared across the `MediaSource `and `SourceBuffer `objects.  Is there a preferred way to express that?

I agree that step 4 of the 2.4.6 **Duration change** algorithm should be revised to return an error.  Thanks.

The note under step 4 seems like it belongs under 3.5.7 **Range removal** then, since we no longer directly run the range removal algorithm.  I'm not aware of any specific problem caused by leaving cues that are outside the new duration range.  Are you?

**Comment by wolenetz** [comment]
@jdsmith3000 As part of reviewing #65, paging in our separate email thread and the context in this issue, I took a look at the last paragraph in https://github.com/w3c/media-source/issues/19#issuecomment-180093676 : I don't think that note belongs in either duration change or range removal algorithms. Since we're explicitly disallowing reductions of duration to a value below the highest *end* timestamp across all SourceBuffer.buffered, then there's no possibility of a partially truncated frame in any SourceBuffer occurring in duration change algorithm. Further, with this disallowance of duration reduction causing truncation, the duration in the context of the range removal algorithm' *must* be >= the highest end timestamp across all SourceBuffer.buffered (and is used as the default remove end timestamp), so there can be no possibility of range removal partially leaving buffered a coded frame that has end timestamp > duration (so no cues that begin before and end after duration). Your PR is looking pretty good. I'll finish posting my first round of comments to it shortly.

**Comment by wolenetz** [comment]
For posterity, see also https://github.com/w3c/media-source/issues/26#issuecomment-211635911 for summary of our "separate email thread" that I mentioned in https://github.com/w3c/media-source/issues/19#issuecomment-215600893
