### ISSUE TITLE
Can we expose MediaSource in DedicatedWorkerGlobalScope and SharedWorkerGlobalScope?

### ISSUE THREAD

**Issue by guest271314** [w3c/media-source#192]
Can we expose MediaSource in DedicatedWorkerGlobalScope and SharedWorkerGlobalScope? 

Use cases include requesting, processing and editing media in a different context which could be posted to a separate context or server.

**Comment by wolenetz** [comment]
I believe this is a duplicate of #175.
If I'm incorrect, please re-open this issue with a note.
