### ISSUE TITLE
HTMLVideoElement.currentTime does not reflect actual time video has played at Firefox 57 (trunk)

### ISSUE THREAD

**Issue by guest271314** [w3c/media-source#198]
With `SourceBuffer.mode` set to `"sequence"` and following over ten seconds of video playback at `<video>` element and calling `.endOfStream()`, `HTMLVideoElement.currentTime` is four seconds, not expected ten seconds. `timeupdate` event is not dispatched though media is still playing.

To reproduce https://github.com/guest271314/recordMediaFragments/blob/master/demos/recordMediaFragments.html

Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1398028

**Comment by jyavenard** [comment]
This site is about lodging issues related to the Media Source Extension *spec*. It is not to report user agent implementation issues.

Please stop hijacking this facility for unrelated purpose. thank you

**Comment by guest271314** [comment]
@jyavenard Not "hijacking" anything. Just asking the individuals with most experience using `MediaSource` questions concerning `MediaSource`.  Cannot guarantee that will not ask questions when have them. If you or others decide the question is not applicable to the specification you can close the thread.
