### ISSUE TITLE
Clarify asynchronicity in duration change algorithm when reducing duration

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#20]
Migrated from w3c bugzilla tracker. For history prior to migration, please see:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27982

It was previously assigned to Adrian Bateman. Editors will sync soon to determine who to take this bug.

**Comment by jdsmith3000** [comment]
We plan to disallow aborts of a range removal to insure results are deterministic, and separate range removal from duration changes that would currently do an automatic remove. That affects both this issue and [Issue 19](https://github.com/w3c/media-source/issues/19).

**Comment by jdsmith3000** [comment]
See latest comment in issue #19.  We want to return an error on abort() during range removal.

**Comment by wolenetz** [comment]
@jdsmith3000 fixed this with https://github.com/w3c/media-source/commit/b386c1ca8637e8370f5817e35d71cb68d8854425 merged in https://github.com/w3c/media-source/pull/65
