### ISSUE TITLE
MSE does not play well with fragmented MP4 containing incremental base decode time (tfdt). It plays only I Frame it seems. Jumping B Frames.

### ISSUE THREAD

**Issue by alok-anand1** [w3c/media-source#208]

**Comment by jyavenard** [comment]
If you could please provide a test case, and check on all browsers. I doubt this is a MSE spec issue which is what this issues should be about.

**Comment by wolenetz** [comment]
In absence of repro case or further response, I'm closing this. Please file another issue referencing this is this is still a spec issue. To me, it sounds like it's an implementation issue, and if so, please file a bug against the implementation as the preferred route forward.
