### ISSUE TITLE
Normative section "Definitions" is contained in a non-normative section

### ISSUE THREAD

**Issue by saschanaz** [w3c/media-source#227]
https://w3c.github.io/media-source/#definitions

The section "Definitions" includes several SHOULD and MUST but is contained inside a non-normative section "Introduction". It should be separated as other specs e.g. [EME](https://w3c.github.io/encrypted-media/#definitions) does.

**Comment by chrisn** [comment]
This has now been moved to a top-level section, after Introduction.
