### ISSUE TITLE
Coded frame removal algorithm may introduce discontinuity at end of current coded frame group

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#23]
Migrated from w3c bugzilla tracker. For history prior to migration, please see:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28557

**Comment by jdsmith3000** [comment]
We generally support resuming with a random access point to avoid discontinuity issues like this one.  Matt's proposal does that, and also resets the timestamps when a frame removal discontinuity can occur.  That change makes sense.

These steps would be added to the frame removal algorithm when the decode timestamp == the last decode timestamp:

1) If mode equals "segments": Set group end timestamp to presentation timestamp.
2) If mode equals "sequence": Set group start timestamp equal to the group end timestamp.
3) Unset the last decode timestamp on all track buffers.
4) Unset the last frame duration on all track buffers.
5) Unset the highest end timestamp on all track buffers.
6) Set the need random access point flag on all track buffers to true.

**Comment by wolenetz** [comment]
That sounds good to me (akin to my proposal in https://www.w3.org/Bugs/Public/show_bug.cgi?id=28557#c1). To clarify, these steps would be added to the frame removal algorithm when [the frame being removed has] decode timestamp == the last decode timestamp [for that frame's track].
