### ISSUE TITLE
Update editors for v2

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#246]
I will continue editing. @mwatson2 will continue editing.
We still need to know from MSFT who they will have as their new editor.

**Comment by wolenetz** [comment]
Current information is that it will just be @mwatson2 and myself as co-editors for the V2 MSE spec.

**Comment by wolenetz** [comment]
https://github.com/w3c/media-source/commit/8844c2ec5c0554323eacf907b29bb947d7c3c7e0#diff-3d8aef5368ad0d78966832e7189732dc fixed this issue already.

**Comment by mwatson2** [comment]
Matt,

Although I have been very absent from discussions these recent
months (years!), I am still able to help with editing. You can assign
things to me if you like.

...Mark

**Comment by wolenetz** [comment]
@mwatson2  - excellent. I've sent a request to setup a triage session for V2 in email. Let's get the ball rolling together (it's been moving, but just on MSE-in-Workers experimental implementation in Chromium, not spec, recently).
