### ISSUE TITLE
Are MSE incubations in WICG still ongoing?

### ISSUE THREAD

**Issue by tidoust** [w3c/media-source#254]
The codec switching feature in MSE is explictly in scope of the Media Working Group, and I believe mse-in-workers-using-handle and eviction policies are as well. If so, it would be good to merge the content from the WICG repo into the W3C repo, and flag (or delete) the WICG repo as no longer being worked upon. @wolenetz, @mwatson2, how would you like to proceed?

**Comment by wolenetz** [comment]
@tidoust - yes, those features you mention in the WICG are on my plate to get merged into upstream Media WG's MSE repo for inclusion in MSE v2. I'll assign this issue to myself to help ensure it is tracked. Thank you for filing this issue. @mwatson2 please let me know if you have any concerns or feedback.

**Comment by chcunningham** [comment]
Hi @wolenetz, just checking in. MediaCapabilities would like to reference changeType() in signalling what media pipelines support codec switching.

**Comment by chrisn** [comment]
I think everything from WICG has been brought here (although work is still needed on some of the features), so we can close this. The [WICG repo](https://github.com/wicg/media-source/) has been archived.
