### ISSUE TITLE
Per spec, no frame will be removed when changing mediasource duration

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#26]
Migrated from w3c bugzilla tracker. For history prior to migration, please see:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28727

**Comment by wolenetz** [comment]
It looks like there is strong overlap with some of the other abort on duration reduction issue(s) that Jerry is working on right now.

**Comment by jdsmith3000** [comment]
We intend to separate range removal operations from duration reductions, and that should resolve the primary concern in https://www.w3.org/Bugs/Public/show_bug.cgi?id=28727.

**Comment by jdsmith3000** [comment]
@wolenetz and I had a private discussion on this bug.  This comment summarizes the discussion.

Comments apply to issues #19, #20 and #26.  The issues generally are:
 
- Shortening duration doesn’t work properly with range removal
- `abort()` similarly doesn’t give deterministic results during removes
- Completing range removals async can lead to duration change errors
 
The async issue is a result of a change sometime back to have Coded Frame Removals complete asynchronously when called from Range Removal, with control returned to the caller.
 
A general proposal I previously reviewed with @wolenetz was:
 
-  Require running `remove()` to run Range Removal (by removing automatic removal from Duration Change)
  - From @wolenetz: More precisely, change the spec so only remove() runs range removal algorithm. (Remove the conditional async race problem from the duration change algorithm.) Note that coded frame removal algorithm (which is not the larger range removal algorithm) will still be used by coded frame eviction algorithm as part of append processing.
- Insert a note in Duration Change about not performing automatic range removal (i.e. `remove()` required first)
  - From @wolenetz: Two bullets down from this covers this bullet better, right? (Throw InvalidStateError !! prior to step 3 "Update duration to new duration" !!, if "new duration" < the highest end time reported by the buffered attribute across all SourceBuffer objects in SourceBuffers.
- Duration change would still check for a reduced duration, and possibly throw an error if `updating `is true (i.e. a `remove()` is in process)
  - From @wolenetz: Don't introduce this redundancy. In fact, we run duration change algorithm *to increase duration* as part of coded frame processing, which is part of append processing, which indeed occurs while updating is true. We already have the MediaSource.duration InvalidStateError gate in the attribute setter.
- Throw an `InvalidStateError `exception on Duration Changes that require range removal (revised step 4)
  - From @wolenetz: See two bullets up from here. tl;dr: correct, but spec text shouldn't have "that require range removal"; rather I put some suggested text a couple bullets up from here. 
- Return an error from `abort()` if it runs when range removal or coded frame removal algorithms are running (new step 3.1 in `abort`)
  - From @wolenetz: Only error if when *range removal* is occurring. Note that coded frame removal algorithm legally runs as part of coded frame eviction algorithm, as part of append* processing, which needs to be abortable.

I'm working on a PR for this.

**Comment by wolenetz** [comment]
As I mentioned just now on related #19, your PR (#65) is looking pretty good. I'll finish posting my first round of comments to it shortly.

**Comment by jyavenard** [comment]
Maybe I should open a new bug, but seeing that abort() is mentioned here. I believe abort() shouldn't interrupt the Coded Frame Processing Algorithm ; as abort() as it's currently described results in a non deterministic in regards to which frames have actually been added to the source buffer. Rather than interrupt something that is really non-interruptable, it should only guarantee that the next call to appendBuffer or modification to timestampOffset or appendWindow will succeed.

**Comment by wolenetz** [comment]
@jdsmith3000 fixed this with b386c1c merged in #65

**Comment by jyavenard** [comment]
@jdsmith3000 I see that there is still a "If a user agent is unable to partially render audio frames or text cues that start before and end after the duration, then run the following steps:"

which then talk about removing the partial frames. But how could this ever happen if we are to throw an invalid state error when "If new duration is less than the highest starting presentation timestamp of any buffered coded frames for all SourceBuffer"

shouldn't that entire paragraph be removed now that changing the duration  can't remove frames?

**Comment by jdsmith3000** [comment]
@jyavenard We didn't do anything to change the underlying reasons for the audio frame and text cue special case.  Previously, a remove was automatically triggered (with some structural problems) that ultimately called the **Coded Frame Removal Algorithm**.  Our change has the app do this by calling `remove()` to resolve the structural problems, but that still uses the same **Coded Frame Removal Algorithm** algorithm, step 3 of which says:

> Remove all media data, from this track buffer, that contain starting timestamps greater than or equal to start and less than the remove end timestamp.

I believe this step deals effectively with video frames, but can can result in audio frames or text cues that start before and end after the duration, even if removes are properly executed by the app.
