### ISSUE TITLE
Consider updating Acknowledgements section

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#335]
I think @padenot, @marcoscaceres, and probably more (such as https://github.com/w3c/media-source/graphs/contributors) deserve inclusion.

**Comment by chrisn** [comment]
I agree, so I've made a PR to add anyone from https://github.com/w3c/media-source/graphs/contributors not already mentioned

**Comment by jyavenard** [comment]
I'm not in the contributors either :)

**Comment by chrisn** [comment]
The current phrasing is "The editors would like to thank ... " so the list only includes non-editor contributors.
