### ISSUE TITLE
InvalidAccessError usage is questionable

### ISSUE THREAD

**Issue by ddorwin** [w3c/media-source#34]
Most/all uses of `InvalidAccessError` should be replaced with `TypeError` or other values. See w3c/encrypted-media#103 for more information.

**Comment by jdsmith3000** [comment]
This is a non-controversial change to use `TypeError` where it's appropriate.  Explanatory language from the referenced EME issue is:

TypeError is defined in https://tc39.github.io/ecma262/#sec-native-error-types-used-in-this-standard-typeerror. It is the "default" error type, for cases when something goes wrong and you don't expect authors to do any switching logic on  err.name . It's not just used for type-system errors as you might expect. Invalid values of any type generally fit under TypeError (unless you really want to call out a specific facet of their invalid-ness for authors to switch on and recover from). IIUC, so would data that cannot be sanitized.

**Comment by wolenetz** [comment]
This might be considered a breaking change.

**Comment by jdsmith3000** [comment]
It's our general view that breaking changes are best done now, rather than after a v1 spec is finished.  

I see 12 `InvalidAccessError `instances in the spec.  I'll prepare a change to move them to `TypeError`.

**Comment by jdsmith3000** [comment]
@Wolenetz I've got commits on two issues under PR #47 because I didn't use a branch to create them.  I think it is simplest to leave them combined for these changes.  I'll use branches for editing MSE going forward.

**Comment by jdsmith3000** [comment]
PR #47 resolved this issue in addition to issue #23.
