### ISSUE TITLE
Normative or informative definitions

### ISSUE THREAD

**Issue by chrisn** [w3c/media-source#347]
All of the byte stream format specs (such as [this one](https://w3c.github.io/mse-byte-stream-format-isobmff/)) have ReSpec warnings because they refer to informative definitions in the MSE spec, e.g., "media segment", "initialization segment".

Should we make these definitions normative - e.g., by moving the current section 1.1 Definitions to a new section 2, so it's outside the informative section 1 Introduction? Some of the definitions include normative requirements on implementations.

**Comment by tidoust** [comment]
+1 to make the definitions normative. On top to the byte stream format specs, the MSE spec itself references these informative definitions from within normative sections and algorithms, which isn't ideal either.

**Comment by chrisn** [comment]
Resolved in #352
