### ISSUE TITLE
Inaccessible diagram

### ISSUE THREAD

**Issue by plehegar** [w3c/media-source#44]
From
  https://lists.w3.org/Archives/Public/public-html-media/2016Jan/0000.html

[[
The diagram in this document should be made accessible. There
are several ways to achieve this, including accessible vector graphics
with SVG, a link to an external description (standard <a href> or
@longdesc), or an in-page description of the graphical content.

	a.)	We provide for your reference a draft textual diagram
	description, though our draft requires enhancement as per b.)
	below. The draft description is available at:

	http://lists.w3.org/Archives/Public/public-apa/2016Jan/0014.html

	b.)	In addition to a textual description of your diagram for
	the benefit of those readers who cannot see it, wWe find the
	diagram also does not clearly convey its meaning and may benefit
	significantly from redesign. Please reconsider what you're
	trying to convey and determine if there is a more intuitive way
	to present the data.  Please clearly label your switches,
	connector endpoints, and relationships, e.g. What are the three
	dots under the video decoders? Are all the audio decoder
	switches open or is that a drawing error? What is the green
	circled X that the audio decoders are pointing to? What are the
	triangles? What is the meaning of the different colors of
	SourceBuffers? What is the viewer expected to learn from this
	diagram?

	c.)	Please consider creating this diagram using SVG. We
	believe it is actually an excellent candidate for the accessible
	graphic markup approaches being defined by the joint ARIA and
	SVG Task Force.[2] One member of this TF has already offered to
	assist, should you decide on SVG.
]]

**Comment by yfuna** [comment]
I got additional information about accessible SVG from Janina and the APA group:

- Introductory materials: https://lists.w3.org/Archives/Public/public-apa/2016Mar/0024.html
- Examples: https://lists.w3.org/Archives/Public/public-apa/2016Mar/0027.html

@chaals and @fredesch will help us evaluate if accessible SVG is a feasible way for us to improve the diagram schedule-wise and complexity-wise.

**Comment by yfuna** [comment]
I've just created an SVG version of the diagram, whose markup is clean and well-structured enough to implement accessibility features mentioned in the materials above: https://github.com/yfuna/media-source/blob/inaccessible_diagram/pipeline-model-structured-for-a11y-impl.svg

I'll start talking with @chaals and @fredesch about their advice at this stage as well as asking the WG members about any ideas to make the more diagram more descriptive and easy to understand.

**Comment by chaals** [comment]
After a 1-minute skim of this it looks like a really great start, with a bunch of good features already there. Thanks @yfuna! I'll try to give a few extra pointers this week.

**Comment by paulbrucecotton** [comment]
@chaals and @fredesch:  Any recommendations on how to ensure this SVG diagram is truly accessible?

**Comment by paulbrucecotton** [comment]
@yfuna: Since we have not gone any further advice from @chaals or @fredesch in the last week, I suggest we implement this revised diagram and then close this issue.

**Comment by paulbrucecotton** [comment]
@yfuna and @plehegar:  Please confirm that we can implement this revised diagram and close this issue.

**Comment by wolenetz** [comment]
Taking this one to do a few cleanups:
1) Resize the svg (at least in the html) to fit the same height/width as the previous png (since the svg commit as-is is to wide on both Edge and Chrome to fit portrait 8.5x11" print preview).
2) regenerate the index.html
3) merge the branch to gh-pages

**Comment by plehegar** [comment]
I removed the size in the SVG so that the UA can use the right size and take advantage of the SVG.

**Comment by wolenetz** [comment]
Thanks, @plehegar et al, for getting this done. I rebased and landed it as https://github.com/w3c/media-source/commit/1f80b6e98d13acc106d5da80a771b6e4756d971c. One minor comment: MSE's editor's draft is actually in the index.html. media-source.html just redirects to that index.html (so I regenerated the correct draft as part of rebasing and landing this.)
