### ISSUE TITLE
Better abstract/introduction?

### ISSUE THREAD

**Issue by plehegar** [w3c/media-source#45]
From
  https://lists.w3.org/Archives/Public/public-html-media/2016Jan/0000.html
[[
We would request greater use of prose to describe what the API
is doing. This is needed both to help the reader understand what is
being specified, but also to test whether the proposed API actually
meets its intended purpose.
]]

**Comment by wolenetz** [comment]
This looks like V1NonBlocking per step 1 of our triage [process](https://lists.w3.org/Archives/Public/public-html-media/2016Mar/0003.html).

**Comment by jdsmith3000** [comment]
I added a very simple introduction description, just above the diagram.  I did not attempt to add a detailed text description of the diagram itself.

**Comment by wolenetz** [comment]
See my comment at https://github.com/w3c/media-source/pull/134#issuecomment-238345364, where I note that I also landed 39795b688861fc345f555dfa9228131c5d3c2ed1 as part of the fix for this (to retain the normative reference to HTML51 which @jdsmith3000's PR had accidentally removed).
