### ISSUE TITLE
Add names to Acknowledgements

### ISSUE THREAD

**Issue by jdsmith3000** [w3c/media-source#48]
In https://github.com/w3c/encrypted-media/issues/109#issuecomment-185853494, Kazuyuki Ashimura (Web and TV IG Team Contact) requested adding names to MSE **Acknowledgments** for individuals that contributed to IG specs that reference MSE.

Names requested to be added are:

•Clarke Stevens, CableLabs (MPTF moderator)
•Hiroyuki Aizu, Toshiba 
•Kaz Ashimura, W3C 
•Richard Bardini, Intel
•Russell Berkoff, Samsung Electronics
•Pablo Cesar, CWI
•David Corvoysier, Orange
•Francois Daoust, W3C
•Franck Denoual, Canon Research Centre France
•Davy Van Deursen, Ghent University, IBBT
•Jean-Claude Dufourd, Telecom Paristech
•Jerry Ezrol, AT&T
•Narm Gadiraju, Intel
•Juhani Huttunen, Nokia
•Hyeonjae Lee, LG Electronics
•Jason Lewis, Disney
•Jan Lindquist, Ericsson
•David Mays, Comcast
•Nilo Mitra, Ericsson
•Giuseppe Pascale, Opera
•Youngsun Ryu, Samsung Electronics

**Comment by jdsmith3000** [comment]
Triaging per the new [MSE & EME Spec Issue Triage Process](https://lists.w3.org/Archives/Public/public-html-media/2016Mar/0003.html).

We still need to reach agreement on how this should be handled, but it's necessary to resolve for version 1.

**Comment by wolenetz** [comment]
This looks to me more like v1-nonblocking per the triage process.

**Comment by jdsmith3000** [comment]
Agreed.

**Comment by jdsmith3000** [comment]
From w3c/encrypted-media#109:

> After determining that other W3C specifications normally only acknowledge WG participants and those in the public that were DIRECTLY involved in the specification work in their Acknowledgement sections, the HME WG Chair and Editors have decided to follow this practice.
This means that we will NOT be adding the list of Web & TV IG members you provided to the EME or MSE Acknowledgement sections. 

This issue is being closed without change.

**Comment by wolenetz** [comment]
I concur. Thanks @jdsmith3000
