### ISSUE TITLE
Byte Stream Format pages still have "file a bug" buttons that link to Bugzilla

### ISSUE THREAD

**Issue by ddorwin** [w3c/media-source#49]
These buttons need to be removed like they were for the main spec.

**Comment by jdsmith3000** [comment]
Triaging per the new [MSE & EME Spec Issue Triage Process](https://lists.w3.org/Archives/Public/public-html-media/2016Mar/0003.html).

This does not appear to be a difficult issue to resolve.

**Comment by wolenetz** [comment]
I agree this looks like V1NonBlocking.

**Comment by wolenetz** [comment]
It looks like something like 1d84d693c0a681ddb45a4d5e51b952a860b0fda8 needs to be done to the various byte stream format specs (and the byte stream format registry).
