### ISSUE TITLE
ISO BMFF Byte Stream Format requires avc1-4 support

### ISSUE THREAD

**Issue by ddorwin** [w3c/media-source#50]
https://w3c.github.io/media-source/isobmff-byte-stream-format.html#iso-init-segments normatively says:
>The user agent must support parameter sets (e.g., PPS/SPS) stored in the sample entry (as defined for avc1/avc2), and should support parameter sets stored inband in the samples themselves (as defined for avc3/avc4).

There are several issues:
* User agents are required to support parameter sets.
* User agents must do so according to avc1-4.
* An example ("e.g.") is provided in normative text.

Ideally, the format specification would not need to be updated to handle new specifications. Is there a way to accomplish the purpose of this text in another way? Perhaps an example in a non-normative Note will provide the necessary context for a more general statement.

**Comment by jdsmith3000** [comment]
I think there's a normative expectation here though that parameter sets are supported so that content can be properly decoded.  The "e.g." aspect above does seem incorrect, and perhaps the explicit avc 1-4 references could be removed to make this guidance more general.

**Comment by jdsmith3000** [comment]
Triaging per the new [MSE & EME Spec Issue Triage Process](https://lists.w3.org/Archives/Public/public-html-media/2016Mar/0003.html).

This does not appear to be a difficult issue to resolve.

**Comment by wolenetz** [comment]
FWIW, I agree this looks appropriately triaged to V1NonBlocking.
