### ISSUE TITLE
The published (TR/) spec references the Byte Stream Format Registry in GitHub

### ISSUE THREAD

**Issue by ddorwin** [w3c/media-source#51]
Is a stable reference required? I recall there was a dated URL. @plehegar has proposed (https://github.com/w3c/encrypted-media/issues/104#issuecomment-184855413) a new location for the EME registry that might be better than the previous dated URL.

**Comment by ddorwin** [comment]
The reference is at https://www.w3.org/TR/media-source/#bib-MSE-REGISTRY.

**Comment by paulbrucecotton** [comment]
That reference is in Appendex A.2 Informative references.  Personally I don't see why we have to worry about a "dated reference" for an informative reference.  Let's NOT give ourselves unnecessary work when we already have lots of MSE technical issues to work on.
