### ISSUE TITLE
Use RFC 2119 words

### ISSUE THREAD

**Issue by ddorwin** [w3c/media-source#52]
ReSpec supports [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt) words ("MUST", "MUST NOT", etc.). If such words are capitalized, ReSpec will format them in a way that indicates their importance. Neither MSE or the Byte Stream Format pages appear to use these.

**Comment by paulbrucecotton** [comment]
We managed to get thru Last Call without any complaining about this so I have to wonder how important this issue is.  I recommend we do not block MSE progress on this kind of issue.  We have LOTS of other more technical matters that have been languishing for way to long.

**Comment by wolenetz** [comment]
FWIW, I agree this looks appropriately triaged to V1NonBlocking.

**Comment by wolenetz** [comment]
While doing this, it would be good to also include a reference to RFC2119 like was done in https://github.com/w3c/encrypted-media/pull/254

**Comment by wolenetz** [comment]
Hmm. I'll file another issue to get the bytestream specs also updated to use RFC2119 key words with conformance sections of their own...
