### ISSUE TITLE
Best practice for detaching?

### ISSUE THREAD

**Issue by joeyparrish** [w3c/media-source#53]
How should an application detach MediaSource from the media element?  In practice, I have been setting `video.src = ''`, but it is unclear from the spec if there should be a better way.

There is an algorithm called "Detaching from a media element", but I don't understand how I am supposed to trigger it if at all.

**Comment by jdsmith3000** [comment]
Clearing the src is reasonable in order to detach the MSE mediasource.  However, while  setting src=””  will work, we believe it is not the recommended way to clear the src attribute.

It may be better to call:   `mediaElement.removeAttribute(”src”);`

**Comment by ddorwin** [comment]
In general, you may also need to call `load()` - see [Best practices for authors using media elements](https://www.w3.org/TR/html5/embedded-content-0.html#best-practices-for-authors-using-media-elements). I can't say for sure whether that is required in to "detach MediaSource," though.

**Comment by joeyparrish** [comment]
I had [tried `removeAttribute('src')` in the past](https://github.com/google/shaka-player/issues/80#issuecomment-104452250), but never followed by `.load()`.  That seems to do the trick.  Thanks, everyone!
