### ISSUE TITLE
CTS vs DTS, which is correct?

### ISSUE THREAD

**Issue by joeyparrish** [w3c/media-source#54]
I could not find any information in the spec about whether `buffered` should give the DTS or the CTS of the appended frames.  Firefox and Safari show CTS, while Chrome and IE/Edge show DTS.  Is one or the other to-spec, or are both valid implementations that applications must deal with?

**Comment by dwsinger** [comment]
hm.  I think decoding timestamps are an internal (usually ignored) artefact;  decoders generally want things in decoding *order* but it's the presentation (composition) timestamp that is the external contract.

just random thoughts

**Comment by wolenetz** [comment]
This is a known Chrome MSE issue, part of a related group of issues: see
https://bugs.chromium.org/p/chromium/issues/list?q=label:MSEptsdtsCleanup

PTS (which, I believe equates to CTS) is called for in some cases where
Chrome uses DTS. This has our attention to be fixed soon, within a few
months.

Matt

**Comment by joeyparrish** [comment]
@wolenetz, thanks for the link.  So officially, PTS/CTS for buffered ranges is in-spec, not DTS?

**Comment by wolenetz** [comment]
@joeyparrish, PTS is the only thing that really makes sense to me to use. Even the HTML5 spec is unclear (it doesn't mention CTS, PTS or DTS), and linkages to .currentTime and .seekable imply (to me) that PTS/CTS is intended for those, similarly.

A little Chrome history on why Chrome has these conflated in places: for early prototypes of MSE in Chrome, WebM and other stream types (where there's commonly no distinction for DTS and PTS) were used and implemented towards. Obviously, conflating PTS with DTS is not ideal, and we have plans to fix this in Chrome soon.

@jdsmith3000, @mwatson2 : Do you think MSE spec needs explicit clarification on this? For the pieces extending HTML5, MSE spec implicitly assumes PTS is meant. Where the concepts of PTS and DTS are unique to MSE vs HTML5 (e.g. the coded frame processing algorithm), the MSE spec is explicit about which is meant.

If no explicit clarification is needed, I recommend WontFix.

**Comment by wolenetz** [comment]
I'm thinking WontFix is appropriate for this issue. Mark/Jerry?

**Comment by jdsmith3000** [comment]
I am confirming with others here.  Your rationale about PTS makes sense me, but at least on the face, it appears there's a difference in interpretation of the proper timestamp to use.

**Comment by joeyparrish** [comment]
It seems that Chrome, IE 11, and Edge 13 are all reporting DTS at the moment.  There are already bugs files on Chrome for this, but I can't seem to find any filed on IE/Edge.  Should I put together a demo/repro and file a bug on Microsoft Connect?

**Comment by jdsmith3000** [comment]
I've gotten an update on Edge.  It uses DTS intentionally as those values are in order.  Presentation Time Stamps (PTS), can be out-of-order due to presence of bi-directional prediction (B) frames.  As MSE `buffered` is a time range, it makes sense to use time that is ordered.

We don't see a problem with using DTS.  The PTS values will be the same as the DTS just out of order.   The H.264 decoder reorders the frames to put them in PTS order, but it must receive them in DTS order.

**Comment by mwatson2** [comment]
It should absolutely be presentation time, which is Composition Time (CTS) as modified by any Edit Lists. This is the only notion of time which is comparable across streams.

**Comment by joeyparrish** [comment]
This came up through a Shaka Player issue.  Here's the results of a test I did comparing implementations:
https://github.com/google/shaka-player/issues/286#issuecomment-190991075

We're not really even sure if it is correct for the content in question to begin with a non-zero PTS, but the difference across browsers gave me pause.

**Comment by mwatson2** [comment]
@jdsmith3000 It's strange to call presentation timestamps "out of order": those are the timestamps that determine the times and thus the order in which fames are presented. Decode Timestamps in mp4 in fact only really communicate the decoding *order*, which may be different from presentation order: there is no requirement to actually decode at the times that the DTSs specify.

It's not correct that PTS and DTS are the same but in a different order. If there is no Edit List and there is frame reordering this will likely not be the case. Edit Lists do typically bring them into alignment, but only certain groups of frames will have the property that "PTS and DTS are the same but in a different order".

@joeyparrish It is certainly correct and common for content to begin with non-zero CTS. I don't believe there is anything wrong with the first PTS also being non-zero. Indeed if you have a piece of content which is an except of a larger (encoded) piece, then it may be unlikely that the first frame should be displayed at exactly the start of the first audio packet, so probably the first video PTS is non-zero.

**Comment by wolenetz** [comment]
Triaging for v1 under step 6 of the [process](https://lists.w3.org/Archives/Public/public-html-media/2016Mar/0003.html).

**Comment by jdsmith3000** [comment]
I dug a bit more and my understanding still supports using DTS for `buffered` time ranges.

If there are no b-frames in an MP4, then DTS == PTS.  If, however, the content uses b-frames, then the samples are out-of-order in the MP4 container in terms of PTS, but in order per DTS.  Frames always come out of the demux in DTS order.  If they are not in PTS order, the decoder reorders the frames so that they are ultimately presented in order.

Eg.  if you have 7 samples in MP4 they might come out of the demux like this (in ms units):

DTS:  0, 33, 66, 100, 133, 166, 200
PTS:   0, 66, 33, 133, 100, 200, 166

The decoder re-orders them so they are passed to the renderer sorted by PTS.

**Comment by joeyparrish** [comment]
In the particular case that spawned this discussion, there is no PTS 0:

DTS: *0, 41, 83*, 125, 166, 208, 250, 291, 333, 375, 416, 458, 500, 541, 583, ...
PTS:  *83*, 125, 166, 208, 250, 291, 333, 375, 416, 458, 500, 541, 583, ...

I can attach the segment if that's helpful.

**Comment by jernoble** [comment]
@jdsmith3000 It doesn't make sense to report buffered ranges as DTS, as it implies a client can seek to a time that cannot be displayed.  In the example @joeyparrish provided, if a client appends media data containing single sample with DTS of 0.0, a PTS of 0.0833, and a duration of 0.0833, a DTS-based buffered range would show [0.0 .. 0.083) as buffered, but seeking to time 0.0 would not display that sample, as it is before the presentation time.  If the seekable property is also DTS-based, they would not be able to seek to the presentation time of the sample they just appended.

**Comment by jdsmith3000** [comment]
@joeyparrish: Please do attach a segment that illustrates the time stamps you list.

**Comment by joeyparrish** [comment]
Here's a segment of video with PTS of 83ms and DTS of 0ms according to mp4info v1.3.2.

[v1.mp4.zip](https://github.com/w3c/media-source/files/187222/v1.mp4.zip)

**Comment by jyavenard** [comment]
Firefox MSE uses cts/pts (and IMHO it's as it should be). I reported a bug with web-platform-test related to the buffered ranges test.
The samples mp4 used have a cts > 0, yet the test assume that the buffered range should start at 0 (and likely because that's what Chrome does).
https://github.com/w3c/web-platform-tests/issues/1939

I believe the spec indicates that the buffered range should be constructed from the pts (seeing that all parsing of samples uses "presentation timestamp"). It's also the only thing that makes sense as the decoder will output frames in presentation order.

**Comment by jdsmith3000** [comment]
Given the example that would benefit from PTS, we agree using it makes sense.  I had some concern that lacking a PTS 0 sample might be detected by some sites as a gap, but those I asked indicated that this would not be a problem.

**Comment by wolenetz** [comment]
@jdsmith3000 regarding the potential concern of a gap in a "jagged starting" scenario, Chrome allows a leeway of up to 1000ms later than time 0 to not stall on seeking to time 0. I suggested in [#15 (comment)](https://github.com/w3c/media-source/issues/15#issuecomment-197587438 ) and [comment](https://github.com/w3c/media-source/issues/15#issuecomment-208675688) some clarifications that could eliminate this interop concern (especially in the former comment, item (2)).  I look forward to your response on that issue to help both of these progress towards closure.

**Comment by jernoble** [comment]
@wolenetz FWIW, Safari has a "fudge factor" of 1/24s (or 42ms) in this "jagged start" scenario.  Last I checked, Firefox has a 250ms fudge factor.

**Comment by jyavenard** [comment]
@jernoble not quite for Firefox, it allows a gap of +/- 125ms. We used that value because that's what chrome used at a time :)

**Comment by jdsmith3000** [comment]
@Wolenetz @jernoble Edge allows a 1000ms jaggedness as well.

**Comment by jdsmith3000** [comment]
I think we should clarify the use of PTS in `buffered` time ranges.  In the `buffered` read algorithm, step 4.1 says:

> Let *track ranges* equal the track buffer ranges for the current track buffer.

Where "track buffer ranges" is:

> Each track buffer has a **track buffer ranges** variable that represents the presentation time ranges occupied by the coded frames currently stored in the track buffer. For specification purposes, this information is treated as if it were stored in a normalized TimeRanges object.

Should we edit the ranges description to call out **presentation timestamp ranges**?

What other changes might be useful?

**Comment by wolenetz** [comment]
"track buffer ranges" is already defined in terms of presentation time [1]; it is unambiguous to me, though perhaps we could reinforce it as you suggest in SourceBuffer.buffered read step 4.1.

[1] "Each track buffer has a track buffer ranges variable that represents the presentation time ranges occupied by the coded frames currently stored in the track buffer. For specification purposes, this information is treated as if it were stored in a normalized TimeRanges object."

**Comment by jdsmith3000** [comment]
Step 4.1 in `buffered` seems clear to me, since it references the track buffer ranges description.  I was proposing a minor clarification in the description, changing "presentation time" to a link to the "presentation timestamp" definition.

**Comment by wolenetz** [comment]
Presentation time ranges is not just PTS, but also extends out to the PTS+duration of the last frame in presentation order. IIUC, just replacing (in the track buffer ranges definition) "presentation time ranges" with "presentation timestamp ranges" makes track buffer ranges less clear IMO, because the PTS is just the beginning of the presentation time of a frame. The full presentation time range for a frame is [PTS, PTS+duration).

**Comment by jdsmith3000** [comment]
Do you have a suggestion on where we might clarify that PTS is used for `buffered`?

**Comment by wolenetz** [comment]
I think buffered's usage of track buffer ranges, which uses "presentation time ranges" is sufficient for buffered. Do you think we need to define presentation time ranges in terms of PTS? Notably, it's not "decode time ranges".

**Comment by jdsmith3000** [comment]
I believe it could/should be more clearly stated, based on the discussion in this issue.  I'm looking for where.  We could add a note to the `buffered` algorithm about it using PTS.  Or add normative language, though I have trouble seeing it fit in the `buffered` section directly.

**Comment by wolenetz** [comment]
Perhaps a non-normative note in the definition of track buffer ranges that clarifies that "presentation time ranges" are based on PTS, frame durations, and potentially coded frame group start times for coded frame groups across track buffers in a muxed SourceBuffer (for the latter, this is something I'd like to include as part of #15).

**Comment by jdsmith3000** [comment]
I think your proposal works fine.  In context with the track buffer range paragraph, it would look like:

> Each [track buffer](http://w3c.github.io/media-source/#track-buffer "track buffer") has a ***track buffer ranges*** variable that represents the presentation time ranges occupied by the [coded frames](http://w3c.github.io/media-source/#coded-frame "coded frames") currently stored in the track buffer. For specification purposes, this information is treated as if it were stored in a [normalized TimeRanges object](http://www.w3.org/TR/html5/embedded-content-0.html#normalized-timeranges-object).
> 
> **Note**
> 
> For track buffer ranges, these "presentation time ranges" are based on PTS, frame durations, and potentially coded frame group start times for coded frame groups across track buffers in a muxed `SourceBuffer`.

I'll do a PR if this looks complete.

**Comment by paulbrucecotton** [comment]
@jdsmith3000:  Please go ahead and create your proposed PR.  If @wolenetz has any problems he can comment on your PR.

**Comment by xqq** [comment]
I also want to know, whether the `HTMLVideoElement.currentTime` gives `DTS` or `PTS` in current `audio` or `video` playback position, or an internal clock time?
This seems unclear in HTML5 spec. Maybe there's difference between browsers' implementations?

**Comment by jyavenard** [comment]
I'm having difficulties understanding how there could be any confusion in regards to currentTime between cts vs dts (though I thought the same with the buffered range and any public facing time values).

dts serves no public purpose other than internal data for the decoder.

cts are always monotonically increasing, dts aren't.

**Comment by dwsinger** [comment]
> On Apr 27, 2016, at 2:56 , Jean-Yves Avenard <notifications@github.com> wrote:
> 
> I'm having difficulties understanding how there could be any confusion in regards to currentTime between cts vs dts (though I thought the same with the buffered range and any public facing time values).

I agree.

> 
> dts serves no public purpose other than internal data for the decoder.

agreed, and not often that.  AFAICT no-one actually cares about decode *timestamps*; they take frames in decode *order* and pump them through the decoder to build a reasonably large playout buffer, which they then playout at cts.

> 
> cts are always monotonically increasing, dts aren’t.

well, they both monotonically increase but on different timelines: in decode order, dts increases; in composition order, cts increases. But this is almost stating a tautology.




David Singer
Manager, Software Standards, Apple Inc.

**Comment by wolenetz** [comment]
@dwsinger @jyavenard : I agree. Decode time shouldn't really be exposed via the web API, though it's used in MSE discontinuity detection (in the coded frame processing algorithm), and of course in ordering the media decode within the engine. PTS is the timeline within which buffered, currentTime, seekable, etc report. Not all UAs have done this correctly in all places, Chrome MSE implementation will be getting fixed soon. Since MSE spec mentions DTS as part of coded frame processing algorithm, perhaps this is where the confusion arises. I agree with @jdsmith3000 's proposal in https://github.com/w3c/media-source/issues/54#issuecomment-213182456 and look forward to a PR (@jdsmith3000, assign this to me if you'd rather I produce the PR.)

**Comment by jdsmith3000** [comment]
@wolenetz PR #70 adds the note we'd previously agreed upon to resolve this issue.
