### ISSUE TITLE
Exclude createObjectURL from Service Workers

### ISSUE THREAD

**Issue by inexorabletash** [w3c/media-source#67]
Based on a [Service Worker issue and discussion](https://github.com/slightlyoff/ServiceWorker/issues/688) [File API](https://w3c.github.io/FileAPI/) was recently [updated](https://github.com/w3c/FileAPI/commit/b9c2275df53cf3a808f1f272f3d6134d1b920549) to make the URL creating/revoking methods not be exposed in Service Workers:

```webidl
[Exposed=(Window,DedicatedWorker,SharedWorker)]
partial interface URL { ... };
```

It seems like the same should be done here. @adrianba should be able to provide more context if necessary.

**Comment by paulbrucecotton** [comment]
This issue would appear to be directly related to ISSUE-10 [] which is about how the createObjectURL method is used in MSE.

/paulc

[1] https://github.com/w3c/media-source/issues/10

**Comment by paulbrucecotton** [comment]
@plehegar :  Can you assist in determining how this issue should be triaged ie is this a V1 issue?

**Comment by wolenetz** [comment]
Excluding URL.createObjectURL(MediaSource) from SW makes sense at least for V1, and follows the recent File API change https://github.com/w3c/FileAPI/commit/b9c2275df53cf3a808f1f272f3d6134d1b920549

I'll prepare a PR shortly.

**Comment by Sandwell** [comment]
And how do we store our file URL when we want to use IndexedDB in a service worker to store our app images ?

**Comment by wolenetz** [comment]
@Sandwell I'm a bit unclear on your question: is MSE involved in your scenario, and if so, how?
