### ISSUE TITLE
Array bracket syntax is deprecated

### ISSUE THREAD

**Issue by rainerschuster** [w3c/media-source#68]
The attribute definition

```
readonly        attribute DOMString[]      kinds;
```
in the interface `TrackDefault` should be changed to something like

```
readonly        attribute sequence<DOMString>      kinds;
```

**Comment by paulbrucecotton** [comment]
>readonly attribute sequence kinds;

It looks like GitHub is not displaying this line correctly.  In the email notification I got for this issue the last keyword sequence is followed by "<DOMString>".

/paulc

**Comment by paulbrucecotton** [comment]
W3C WebIDL CR [1] still uses the "[]" syntax.  The referenced "sequence" syntax is defined in WebIDL V2 [2].  It would appear that MSE should probably include an explicit normative reference to a WebIDL specification so that it is clear what syntax is being used.  

Given that we are trying to complete MSE by Sep 2016, I would recommend we continue to reference the W3C WebIDL CR [1] specification and NOT make this suggested change.  We could of course add an informative note about the deprecation in WebIDL V2 of the array syntax.

/paulc

[1] http://www.w3.org/TR/WebIDL/#idl-array
[2] http://heycam.github.io/webidl/#idl-sequence

**Comment by rainerschuster** [comment]
Thanks for pointing this out. In this case it would of course be ok to just reject this issue.

**Comment by paulbrucecotton** [comment]
I propose we mark this issue as VNext so we catch it if we can take up a future version of WebIDL in a future edition of MSE.  And then I suggest we can close this issue since even the commenter is okay with that action.

**Comment by ddorwin** [comment]
I believe the correct reference for the WebIDL CR is https://www.w3.org/TR/WebIDL-1/. This is the one that is currently being pushed through. Is the old CR likely to ever reach REC?

This version does not appear to have arrays or "[]" at all. It does have https://www.w3.org/TR/WebIDL-1/#idl-sequence.

If I am correct that it is unlikely that a version of WebIDL containing arrays will reach REC, we should probably switch to sequence. The necessary change seems very small.

**Comment by paulbrucecotton** [comment]
@plehegar  or @yfuna :  Can you help us understand the status of WebIDL and which version we should normatively reference and thus what "array" syntax we should be using?

**Comment by paulbrucecotton** [comment]
@plehegar: Since Yosuke is offline could you please help here?

**Comment by paulbrucecotton** [comment]
@plehegar : Can you assist in determining how this issue should be triaged ie is this a V1 issue?

**Comment by plehegar** [comment]
Best is to reference WebIDL v1, since it's considered the most stable.
I believe the impact of the change on implementations is relatively minor, if at all. So we could make the change as we see fit imho.

**Comment by paulbrucecotton** [comment]
Given Philippe's input, I now recommend we:
a) mark this issue with the V1 milestone, and
b) change to use the [sequence syntax](https://www.w3.org/TR/WebIDL-1/#idl-sequence) in WebIDL-1.

**Comment by wolenetz** [comment]
While trying to clean up current respec console log errors when rendering media-source-respec.html, I found that the repo's updated (and even the currently live) respec-w3c-common.js has changed the processing of definitionMap. This produces a console error. If I remove the definitionMap entries, then interestingly, there is no console error but the web IDL types like "unrestricted double" no longer are found by our msePostProcessor logic in media-source.js, and consequently no longer link to WebIDL-1.  Any ideas how to clean up the log errors and retain our custom linkage to WebIDL-1? Do we need to migrate to respec's contiguous-IDL at this point to retain this? For V1, should we live with those current log errors and revisit later?

**Comment by plehegar** [comment]
re WebIDL errors: as long as the generated HTML is what you need, I suggest to raise a separate issue, add it in V1NonBlocking and if we get to it, great, otherwise, will get it done in the future. Changing the WebIDL handling will need to get done since the old way is no longer supported but it's probably a two days work job...

**Comment by wolenetz** [comment]
Closing. Though the current editor's draft doesn't have the generated result, subsequent issue landing will regenerate it.  Thanks, @plehegar

**Comment by wolenetz** [comment]
The commit is in a branch currently. @mwatson2 is merging it now.

**Comment by wolenetz** [comment]
Reopening so @wolenetz will track the merging of this tree (including index.html regeneration). @mwatson2 currently doesn't have the sufficient MSE repo credentials.

**Comment by plehegar** [comment]
@mwatson2 should have access now.

**Comment by plehegar** [comment]
btw, I don't regenerate the index.html on my PRs to avoid merge conflicts but could if you folks prefer.

**Comment by wolenetz** [comment]
@plehegar no worries, we'll take care of it.

**Comment by paulbrucecotton** [comment]
@wolenetz , @mwatson2 

What is the schedule to complete this V1 change?

**Comment by wolenetz** [comment]
@paulbrucecotton this issue is closed. The resolution is in the current editor's draft. Per change history, as of May 26: "Issue 68 - Made kinds attribute and ctor argument use sequence type." Do I misunderstand your question?

**Comment by paulbrucecotton** [comment]
Please ignore my question.  I obviously did not see the "CLOSED" flag.
