### ISSUE TITLE
MSE Registry: Establish a update process & home

### ISSUE THREAD

**Issue by plehegar** [w3c/media-source#74]
We have several documents for the MSE registry:
http://w3c.github.io/media-source/byte-stream-format-registry.html
http://w3c.github.io/media-source/webm-byte-stream-format.html
http://w3c.github.io/media-source/isobmff-byte-stream-format.html
http://w3c.github.io/media-source/mp2t-byte-stream-format.html
http://w3c.github.io/media-source/mpeg-audio-byte-stream-format.html

Following https://github.com/w3c/encrypted-media/issues/104 , we should publish as Notes at

https://www.w3.org/TR/mse-byte-stream-format-registry
https://www.w3.org/TR/mse-webm-byte-stream
https://www.w3.org/TR/mse-isobmff-byte-stream
https://www.w3.org/TR/mse-mp2t-byte-stream
https://www.w3.org/TR/mse-mpeg-audio-byte-stream

**Comment by plehegar** [comment]
Once I managed to get the Notes published, I'll go around and ensure we have proper redirects in the right places.

**Comment by paulbrucecotton** [comment]
@plehegar - I have issued an [HME WG CfC ](https://lists.w3.org/Archives/Public/public-html-media/2016May/0035.html) on this matter.  The CfC closes on Tue May 24. Please go ahead with your preparatory work and schedule the publications at a convenient time after May 24.

**Comment by paulbrucecotton** [comment]
[WG Decision](https://lists.w3.org/Archives/Public/public-html-media/2016May/0057.html) supports the publication of the MSE Registry as WG Notes.

**Comment by wolenetz** [comment]
Closing this v1 issue. If we need to revisit in VNext or later milestone, we can have a new tracking issue.
