### ISSUE TITLE
VideoPlaybackQuality is underdefined, leading to interop concerns

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#76]
While looking into #69, we discovered some concerns with the current specification of VideoPlaybackQuality:
- The spec does not say what to do if values cannot be provided, potentially leading to interop issues and/or authors ignoring them.
  - For example: Firefox and Chrome always report corruptedVideoFrames as 0, meaning a value of 0 is meaningless to authors. If this value can’t be calculated by most implementations, maybe it should be removed from the spec. Otherwise, there should be a specification of how to do feature detection. For example, state that implementations should not expose an attribute it cannot support or otherwise indicate it is invalid (a nullable/optional value?).
  - If the implementations are inaccurate, it may be misleading authors.

Note: Moving VPBQ out of MSE spec (per #69), would address this MSE bug.

As further indication that this feature is underdefined:
- Is there no concern or parallel for corrupted **audio** decode? (Perhaps this should be a MediaQualityObject.)
- droppedVideoFrames covers both predecode drop and missing deadline drop:
  - is this distinction relevant to authors, and can all/most implementations cover both types of drops?
  - If not, this value would be unreliable and we need some sort of feature detection.
- Optionality in whether to report corrupt frames as dropped: This allows implementation flexibility, but should implementations be consistent in reporting?

**Comment by mounirlamouri** [comment]
FWIW, the fact that the update mechanism isn't defined sounds like a problem to me. As specified, unless I missed something, developers would have to poll in order to know if the information have been updated.

**Comment by wolenetz** [comment]
Moving to VNext per https://github.com/w3c/media-source/issues/69#issuecomment-221948879

**Comment by mwatson2** [comment]
I propose we close this since Media Playback Quality now has its own [specification](https://w3c.github.io/media-playback-quality/).

**Comment by wolenetz** [comment]
This is not in the MSE spec any longer (as of MSE v1 REC). There is a non-normative note describing where it was being developed further. Implementations likely will retain the legacy implementation as originally defined in MSE.
