### ISSUE TITLE
Add at-risk item "VideoPlaybackQuality" to MSE spec, per recent CfC

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#87]
Per https://lists.w3.org/Archives/Public/public-html-media/2016May/0059.html, this issue tracks adding VideoPlaybackQuality to the list of at-risk items in the spec.

**Comment by jdsmith3000** [comment]
@wolenetz This looks like a simple edit.  If you aren't already doing it, I'll re-assign and do it today.
