### ISSUE TITLE
TrackDefault.kinds attribute cannot have type sequence<DOMString>

### ISSUE THREAD

**Issue by tidoust** [w3c/media-source#91]
(Note: I'm creating a new issue but this basically reopens #68)

Using a `sequence<DOMString>` type for `TrackDefault.kinds` is not possible in practice. All versions of WebIDL explicitly forbid the use of `sequence<T>` types for attributes (because sequences are passed by value, not by reference, which is probably not what you want here):

> Sequences MUST NOT be used as the type of an attribute or constant. 
> http://heycam.github.io/webidl/#idl-sequence

Among other things, this makes the IDL test harness complain that the IDL definition is invalid.

Since `TrackDefault.kinds` is `readonly`, I suspect that you would rather want to use a `FrozenArray<DOMString>` type... but this type is only defined in "Web IDL (Second Edition)" for the time being:
http://heycam.github.io/webidl/#idl-frozen-array

I do not know how to do the same thing if you stick to WebIDL Level 1. That seems impossible to do without the array type... @plehegar, do you know if that's intended and if there's another way?

**Comment by plehegar** [comment]
pinging @travisleithead @ylafon would might have a suggestion here.

**Comment by travisleithead** [comment]
To preserve the current syntactic use-case, `FrozenArray<DOMString>` is definitely the solution you want. However, you are correct that this is not one of the features slated for WebIDL-1.

If you are OK changing the syntax a bit, the workaround using the WebIDL-1 feature set is to transform the readonly attribute into a method, e.g., `TrackDefault.getKinds()` which can return a `sequence<DOMString>`

**Comment by wolenetz** [comment]
@jdsmith3000 or @plehegar Can you take a look at this please while I work on fixing #5? Please assign to yourself. This seems like it might be grounds enough for a substantive change, hence V1 to get it directly on our radar.

@paulbrucecotton FYI.

**Comment by jdsmith3000** [comment]
@plehegar @wolenetz 

I think this is what's needed:

- Replace the sequence<DOMString\> `kinds` attribute in the **TrackDefault** WebIDL with:
	- `DOMString getkinds(sequence<DOMString> kinds);`
- Add a Methods section to **6. TrackDefault Object** (new second 6.3) that describes a simple get method for `getkinds()`.

That's enough to define a method that lets apps query for the `kinds` sequence, but I'm not clear how it can be used for the **3.5.11 Default Track kinds** algorithm.  That runs when the **Initialization Segment Received** algorithm need to determine default kinds for a new track, and currently has language like this:

> If trackDefaults contains a **TrackDefault** object with a type attribute equal to *type* and a byteStreamTrackID attribute equal to byteStreamTrackID, then return the value of the kinds attribute on this matching object and abort these steps.

We wouldn't normally call a method from an algorithm.  Is there a simple solution for this?

@paulbrucecotton FYI.

**Comment by wolenetz** [comment]
@jdsmith3000 Thanks for looking into this. Further to your comment about the **3.5.11 Default track kinds** algorithm, it's callers within the **Intiialization Segment Received** algorithm are expecting an array, not a sequence. Is that also deprecated language that needs to be fixed?

**Comment by plehegar** [comment]
The implementation status of this interface/constructor doesn't seem to look pretty. @jdsmith3000 , is TrackDefault implemented in Edge? As fas as I can tell, only Chrome implements it.

**Comment by plehegar** [comment]
If we change to getkinds(), can we get the implementations to align within the next 6 weeks?

**Comment by wolenetz** [comment]
@plehegar Chrome implements it, and is in the process of integrating it into a compliant initialization segment received algorithm implementation. It's used to populate {SourceBuffer,HTMLMediaElement}.{audio,video,text}Tracks, which in the case of no in-band 'kinds' parse result will rely on an optional, matching TrackDefault supplied by the app to help determine the (potentially multiple) kinds for each bytestream track. Note that this allows potentially N:1 {audio,video,text}Track entries for each bytestream track if there are multiple DOMString values in the matching TrackDefault's kinds for a bytestream track. (IIUC, this N:1 _doesn't_ cause the bytestream track to have multiple track buffers in MSE, just multiple "aliases" in {SourceBuffer,HTMLMediaElement}.{audio,video,text}Tracks to that track buffer.

I believe Chrome can have this (including getKinds(), if that's the route we decide here) within 6 weeks.

**Comment by plehegar** [comment]
I created a pull request to change it to getKinds(). At this point, unless you have substantive changes to make to the pull request (or would like to reject), I suggest to merge the pull as-is and we'll make further editorial tweaks during CR if needed.

**Comment by wolenetz** [comment]
Given potentially lack of implementation alignment (pending @jdsmith3000's response), should we mark TrackDefault, TrackDefaultList, Default track language, Default track label, Default track kinds, and the calls to these in the initialization segment received algorithm as "at risk" right now, and that implementations that do not implement these default track algorithms **must** at least replace them with a trivial implementation that returns an empty string to the caller?

**Comment by wolenetz** [comment]
I've reviewed and merged @plehegar's #94.
However, my [question about marking as "at-risk" this TrackDefaults feature](https://github.com/w3c/media-source/issues/91#issuecomment-225000088) remains open for V1:

@plehegar If I understand correctly (probably FAQ by now, sorry), all these at-risk features don't introduce extra delay into our timeline, right? We just need them to be marked at-risk early enough. However, we'd need a CfC for deciding at-risk. This makes me think we should charge ahead without marking at-risk and just get implementations aligned, to prevent any timeline delay.

@jdsmith3000 can you comment please on Edge alignment plans around TrackDefaults implementation within 6 weeks?

**Comment by plehegar** [comment]
sounds the best approach to me.

**Comment by plehegar** [comment]
Yes, all marked at risk features don't introduce extra delays. Paul ran a separate CfC for at-risk but he could also ask the same question to getKinds as part of asking the question to move to CR.

**Comment by paulbrucecotton** [comment]
Can you give me the exact text that you want to add to the SOTD section with the name of the feature and the hyperlink to its location in the MSE spec?  Preferably you would actually create the PR and execute it to add the text to the SOTD.

**Comment by plehegar** [comment]
I believe the proposal is to add the following to the existing list:
"
* getKinds() https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#widl-TrackDefault-getKinds-sequence-DOMString
"

**Comment by paulbrucecotton** [comment]
That is what I need.  Once we have the regenerated MSE spec I will add this to the CfC.

**Comment by jdsmith3000** [comment]
Edge does not currently support TrackDefaults and would not likely do so in 6 weeks.  This is a general problem with breaking changes to MSE.  We still believe getting the spec right should be the priority, and that it is preferable to make changes now, even breaking ones.

For this specific case, is there even an option not to fix the issue if we have time?  The current spec isn't valid in this area, right?

**Comment by wolenetz** [comment]
@jdsmith3000  : As of merging #94 earlier today, TrackDefaults spec is now valid.
@plehegar @paulbrucecotton : To be clear, if marking at-risk, we may need to mark **all** of TrackDefaults feature area at risk, not just getKinds(). getKinds() alone at risk impacts compliant init segment (which calls it). So, if we mark just getKinds() at risk, then we need to give an alternate version that **must** work for init segment received (e.g. a version that just returns a sequence containing a single empty string). Or if Edge needs all of TrackDefaults feature area marked at risk, then more needs marking at risk in SOTD and mention in CfC: TrackDefault, TrackDefaultList,  Default track language, Default track label, and Default track kinds (and trivial "empty string" versions of those default track language/label/kind algorithms would still need to be available for the initialization segment received algorithm.)

**Comment by wolenetz** [comment]
Updated proposal for at-risk: (We're nearing deadline for this, so I've assumed Edge needs a wider-than-just-getKinds()-at-risk per Jerry's comment https://github.com/w3c/media-source/issues/91#issuecomment-225022160

- TrackDefault related objects, attributes, methods and algorithms: TrackDefault (https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#idl-def-TrackDefault), TrackDefaultList (https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#idl-def-TrackDefaultList), SourceBuffer.trackDefaults (https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#widl-SourceBuffer-trackDefaults), Default track language (https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#sourcebuffer-default-track-language), Default track label (https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#sourcebuffer-default-track-label), and Default track kinds (https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#sourcebuffer-default-track-kinds). Implementations still must at least include trivial versions of these default track language/label/kinds algorithms that are used by the initialization segment received algorithm (https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#sourcebuffer-init-segment-received). These trivial versions would behave as follows: Trivial default track language and Trivial default track label algorithms must return an empty string, and Trivial default kinds algorithm must return a sequence with a single empty string element in it.

**Comment by jdsmith3000** [comment]
Formatting so that I can read it.  :)

> TrackDefault related objects, attributes, methods and algorithms: [TrackDefault](https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#idl-def-TrackDefault), [TrackDefaultList](https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#idl-def-TrackDefaultList), [SourceBuffer.trackDefaults](https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#widl-SourceBuffer-trackDefaults), [Default track language] (https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#sourcebuffer-default-track-language), [Default track label](https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#sourcebuffer-default-track-label), and [Default track kinds](https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#sourcebuffer-default-track-kinds). Implementations still must at least include trivial versions of these default track language/label/kinds algorithms that are used by the [initialization segment received algorithm](https://rawgit.com/w3c/media-source/v1-CR-ready/index.html#sourcebuffer-init-segment-received). These trivial versions would behave as follows: Trivial default track language and Trivial default track label algorithms must return an empty string, and Trivial default kinds algorithm must return a sequence with a single empty string element in it.

Is it allowable to spec a subset of behavior like this, or should we just list the features at risk and publish a subset when/if they need to be removed or modified?

**Comment by wolenetz** [comment]
My intent was to make it clear how initialized segment received algorithm
should behave even if the at-risk trackdefault pieces were eventually
removed.

**Comment by wolenetz** [comment]
Also, for posterity, your reformatting looks good though I haven't checked
the links since I'm mobile.

**Comment by jdsmith3000** [comment]
I suggest we err on the side of putting in the additional at risk.  We can revert it tomorrow if @paulbrucecotton requires.  If you agree, I will do a PR.

**Comment by wolenetz** [comment]
I'm not sure that's what Paul wanted, rather he said earlier on this issue:
"Once we have the regenerated MSE spec I will add this to the CfC."
We have the regenerated spec and agreement on the text for CfC. We don't
need to, iiuc, add in the at risk into spec yet, since it needs CfC still,
right? Also my bandwidth for review this evening is low. I'm offsite.

On Jun 9, 2016 5:04 PM, "jdsmith3000" <notifications@github.com> wrote:

I suggest we err on the side of putting in the additional at risk. We can
revert it tomorrow if @paulbrucecotton <https://github.com/paulbrucecotton>
requires. If you agree, I will do a PR.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/w3c/media-source/issues/91#issuecomment-225061715>, or mute
the thread
<https://github.com/notifications/unsubscribe/ALCtwxbE_SyT0bvkRYZ0k2KrWqVdUWYsks5qKKoBgaJpZM4Iw0e8>
.

**Comment by jdsmith3000** [comment]
On the other at risk items, we merged once I’d sent the links to Paul.  I’m preparing a PR now.  We can either merge it tonight at risk, or hold it until Paul confirms.

**Comment by wolenetz** [comment]
We those other at risk items (EME) ones that had already passed CfC? I
think we should have Paul's confirmation around what to do here. I'll take
a look later tonight at your pr. Thanks Jerry.

**Comment by jdsmith3000** [comment]
I've created a new pull request to list TrackDefault and related items at risk:

> The TrackDefault object and its related objects, attributes, methods and algorithms, including: TrackDefaultList, SourceBuffer.trackDefaults, Default track language, Default track label, and Default track kinds. Implementations still must at least include trivial versions of these default track language/label/kinds algorithms that are used by the initialization segment received algorithm. These trivial versions would behave as follows: Trivial default track language and Trivial default track label algorithms must return an empty string, and Trivial default kinds algorithm must return a sequence with a single empty string element in it.

I did not check the revision history and see that this issue in general isn't on it.  I'll update the pull request to add this.

**Comment by jdsmith3000** [comment]
As long as we hold where we are, the PR is ready to merge with no conflicts.  That can be done later tonight or early tomorrow.

**Comment by wolenetz** [comment]
PR at the moment LGTM. Thanks for preparing. Let's see what @paulbrucecotton wants to do about this. If he wants it merged, then 1) It will be in the editor's draft marked at-risk *before* CfC for marking it at risk, and 2) @plehegar would need to regenerate the v1-cr-ready draft for our re-review.
