### ISSUE TITLE
Steps that fire events at media elements duplicate those in HTML5.1

### ISSUE THREAD

**Issue by tidoust** [w3c/media-source#98]
HTML5.1 specifies the events (e.g. `loadedmetadata`, `loadeddata`, `canplay`, `canplaythrough`)  that are to fire when the `readyState` of a media element changes, see algorithm below the definitions of the ready states in section [4.7.14.7](http://www.w3.org/TR/html51/semantics-embedded-content.html#ready-states)

The Media Source Extensions spec describes conditions that cause the `readyState` of a media element to change. Per HTML5.1, such changes imply firing relevant events at the media element.

The problem is that the Media Source Extensions spec also asks implementations to fire these events. I assume that the goal is to make it clear that changing the `readyState` of the media element also implies firing the events, but the use of normative steps effectively duplicates HTML5.1 and the spec does not say that these steps are intended to replace those in HTML5.1. In other words, an implementation that fires the `loadedmetadata` event twice would just follow the specs. Also, duplicating is error-prone, and for instance I note that the Media Source Extensions spec remains silent on the `timeupdate` and `waiting` events that get fired when the state changes from `HAVE_FUTURE_DATA` to `HAVE_CURRENT_DATA` or less (which can happen at the end of the Initialization Segment Received algorithm for example).

I suggest to leave events up to HTML5.1. This would mean dropping the steps that require events to fire, perhaps replacing them with informative notes such as "Per HTML5.1, changing `readyState` may trigger events on the media element" or something equivalent.

Sections and steps incriminated:
* [2.4.4 SourceBuffer Monitoring](http://w3c.github.io/media-source/#buffer-monitoring)
* [3.5.8 Initialization Segment Received](http://w3c.github.io/media-source/#sourcebuffer-init-segment-received), step 6.3
* [3.5.12 Coded Frame Processing](http://w3c.github.io/media-source/#sourcebuffer-coded-frame-processing), steps 2.2, 3.2, 4.2

Or is there a good reason why these steps need to be in the spec?

Note that, while this touches on normative steps, I don't think it needs to block publication as CR: the update would not change the expected behavior, but merely clarifies the intent and helps avoid misinterpretations.

**Comment by chaals** [comment]
It seems reasonable to note what happens in the spec, but it does make sense to have one document clearly identified as *defining* that.

An informative summary of the normative reference is helpful - but it does need to be kept in synch. People **will** treat it as if it were normative and correct, whatever the reference really says.

**Comment by wolenetz** [comment]
This seems to me to be an editorial change. Please update if you disagree.

**Comment by wolenetz** [comment]
I'll put together a PR that informatively, non-normatively, in MSE spec speaks to the HTML5.1 events on readyState transitions to prevent duplication in purely conforming implementations and to clarify the intent. Thanks for raising this issue, @tidoust

**Comment by wolenetz** [comment]
There is also some duplication of {Audio,Video,Text}TrackList HTML5.1 events in MSE spec: `change`, `addtrack`, `removetrack` which I'll similarly address in the upcoming PR.

**Comment by wolenetz** [comment]
An example of the route I'm taking for this in the PR I'm working on is:
OLD:
`For each AudioTrack object in the SourceBuffer audioTracks list, run the following steps:
Set the sourceBuffer attribute on the AudioTrack object to null.
If the enabled attribute on the AudioTrack object is true, then set the removed enabled audio track flag to true.
Remove the AudioTrack object from the HTMLMediaElement audioTracks list.
Queue a task to fire a trusted event named removetrack, that does not bubble and is not cancelable, and that uses the TrackEvent interface, at the HTMLMediaElement audioTracks list.
Remove the AudioTrack object from the SourceBuffer audioTracks list.
Queue a task to fire a trusted event named removetrack, that does not bubble and is not cancelable, and that uses the TrackEvent interface, at the SourceBuffer audioTracks list.
If the removed enabled audio track flag equals true, then queue a task to fire a simple event named change at the HTMLMediaElement audioTracks list.`

NEW:
`For each AudioTrack object in the SourceBuffer audioTracks list, run the following steps:
Set the sourceBuffer attribute on the AudioTrack object to null.
Remove the AudioTrack object from the HTMLMediaElement audioTracks list.
NOTE
This should trigger AudioTrackList [HTML51] logic to Queue a task to fire a trusted event named removetrack, that does not bubble and is not cancelable, and that uses the TrackEvent interface, at the HTMLMediaElement audioTracks list. If the enabled attribute on the AudioTrack object was true at the beginning of this removal step, then this should also trigger AudioTrackList [HTML51] logic to queue a task to fire a simple event named change at the HTMLMediaElement audioTracks list

Remove the AudioTrack object from the SourceBuffer audioTracks list.
NOTE
This should trigger AudioTrackList [HTML51] logic to Queue a task to fire a trusted event named removetrack, that does not bubble and is not cancelable, and that uses the TrackEvent interface, at the SourceBuffer audioTracks list.`

**Comment by wolenetz** [comment]
PR #132 is ready for review.
